version: '3.3'

services:
  
  pgadmin4:
    image: dpage/pgadmin4:latest
    ports: 
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=alandidiergon@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    restart: always
    links:
      - db
    

  db:
    image: postgres:14.5
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/postgresql/data
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
